### ISSUE TITLE
[iOS] Unable to receive push notifications when app in background.

### ISSUE THREAD

**Issue by sushant-j** [sushant-j/firebase-push-notifications-trial#1]
@EddyVerbruggen - Fixed the issue with app crashing, and reproduced the same scenario where notification is not handled when app is in background. 

Any pointers?

**Comment by EddyVerbruggen** [comment]
I'll try to take a look soon!

**Comment by EddyVerbruggen** [comment]
I'm searching like crazy.. and then encounter this: https://github.com/EddyVerbruggen/firebase-push-notifications-trial/blob/b36b6ff82563199e531bfe384e96dc946ed14786/app/App_Resources/iOS/Info.plist#L55-L56 -- please remove that!

**Comment by sushant-j** [comment]
Thanks a lot for your time @EddyVerbruggen !
Had been struggling with this issue for past 2 days, and a stray flag in the plist file was causing all this :/

**Comment by sushant-j** [comment]
Thanks a lot for your time @EddyVerbruggen !
Had been struggling with this issue for past 2 days, and a stray flag in the plist file was causing all this :/
